### ISSUE TITLE
Issues connecting 

### ISSUE THREAD

**Issue by Samuelseggs** [frealgagu/archlinux.appgate-sdp#9]
I get this error and i'm not able to load my company platform

[2024-10-26T13:19:13.925Z] Error : [VpnDriverLogic - Process:104] 'VPN Driver': Connection failed. Reason 'One or more errors occurred. (The JSON-RPC connection with the remote party was lost before the request could complete.)'.
[2024-10-26T13:19:18.067Z] Debug : [ApplicationContext - LogFunction:82] SHIM: '[segate.company.net - 2]: select timeout, retry'
[2024-10-26T13:19:18.068Z] Debug : [ApplicationContext - LogFunction:82] SHIM: '[segate.company.net - 2]: poll pipe_in//socket_in/ @in=0 @out=0'
[2024-10-26T13:19:18.939Z] Info : [VpnDriverLogic - ProcessInternal:137] 'VPN Driver': Connecting.
[2024-10-26T13:19:18.939Z] Debug : [VpnRpc - Connect:51] RPC already started
[2024-10-26T13:19:18.940Z] Debug : [SocketCommunication - Connect:81] Connect [/var/run/.appgate.driver.socket connection] Exception: Cannot assign requested address
[2024-10-26T13:19:18.940Z] Debug : [JsonRpcFactory - CreateJsonRpc:20] 'VpnRpc': Flushing the pipe
[2024-10-26T13:19:18.940Z] VpnRpc Information: 3 : 
[2024-10-26T13:19:18.940Z] Listening started.
[2024-10-26T13:19:18.940Z] Empower Information: 8 : 
[2024-10-26T13:19:18.940Z] {"id":null,"method":"setModel"}
[2024-10-26T13:19:18.940Z] Empower Verbose: 8 : 
[2024-10-26T13:19:18.940Z] Sent: {"jsonrpc":"2.0","method":"setModel","params":{"view":"connecting","viewData":{"sites":[],"userActions":[],"appShortcuts":[],"setup":{"loading":false,"userApproval":true,"selectedProfile":{"id":"-509302301","name":"Company","server":"segate.company.net","identityProvider":"AD"},"profileSelectionOngoing":false,"errorMessage":null}},"appSettings":{"autoStart":false,"autoSaml":false,"keepCredentials":false,"pinCaching":false,"clientType":"Full","isMultiUser":false,"profiles":[{"id":"-509302301","name":"Company","state":"Active","server":"segate.company.net","idp":"AD","configuredByAdmin":false}],"selectedProfile":"-509302301"},"controllerSettings":{"attentionMode":0,"autoStart":0,"autoSaml":0,"disableEntitlements":false,"disableNewUserOnboarding":false,"disableProfiles":false,"disableQuit":false,"disableRememberMe":false,"disableSignout":false,"disableSuspend":false},"helpUrl":null,"sessionDetails":{"connected":true,"suspended":false,"suspendedByPolicy":false,"ip4":null,"ip6":null,"username":"User","ringfenceEnabled":false,"deviceProxyEnabled":false,"portalBannerShown":false}}}
[2024-10-26T13:19:18.941Z] VpnRpc Critical: 13 : 
[2024-10-26T13:19:18.941Z] Connection closing (StreamError: Reading JSON RPC from the stream failed with IOException: Socket is not connected.). System.IO.IOException: Socket is not connected.
   at Shared.Ssl.SocketCommunication.CheckConnected()
   at Shared.Ssl.SocketCommunication.ReadAsync()
   at Shared.Base.Stream.TextLineStreamToMessageCommunication.ReadMessageAsync()
   at Shared.Base.Stream.CommunicationTextLineStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader, Nullable`1, CancellationTokenSource, CancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16)
   at Shared.Communication.Rpc.Factory.NewLineDelimitedMessageHandlerWrapper.ReadCoreAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.MessageHandlerBase.ReadAsync(CancellationToken cancellationToken)
   at StreamJsonRpc.JsonRpc.ReadAndHandleRequestsAsync()

**Comment by alfabravoteam** [comment]
@Samuelseggs Is this the log for your sdp client? If this belongs to some other application, it cannot be diagnosed here. 

Please, check with your platform provider and, if you can find an odd behavior in sdp, attach the sdp logs

**Comment by Samuelseggs** [comment]
This is from Appgate SDP. However, I was able to figure this out.

This was running on Manjaro.

**Comment by alfabravoteam** [comment]
Interesting! I also run this client on Manjaro. Consider sharing your finding, it might be helpful for others :)

**Comment by Samuelseggs** [comment]
Apparently, the issue was caused by Appgate driver not running. so I did this

sudo systemctl enable appgatedriver.service
sudo systemctl start appgatedriver.service
sudo systemctl status appgatedriver.service

And voila all started to work
